"""
One-off driver: builds the 24 connection x load-case matrix CSVs for the
can-thickness retrofit joint tracks (scenarios A/B, uncorroded + corrosion
composed), from the already-computed stage2_joints_thickness[_corrosion]
caches on the drive -- does NOT re-run Stage 2, reads its cached .npz files
only, same cost class as any other Stage 3 aggregation pass.

Reuses run_pipeline.run_stage3_joints_thickness /
run_stage3_joints_thickness_corrosion unmodified -- those functions already
write the matrix CSVs alongside their existing stage3_joint_damage_
thickness*.csv deliverables (see that module's own docstrings). This script
is just the "here's the exact call I ran" driver, matching run_pipeline.py's
own SELECT-dict philosophy, so a fresh Claude Code session on another
machine (or a person directly) can run one command instead of retyping a
python -c block.

Usage: python build_joint_thickness_matrices.py
Expects: the D:\\OC4_CAMPAIGN drive (or wherever it mounts on this machine --
edit ROOT below if the letter differs) attached, with stage2_joints_
thickness/{A,B} and stage2_joints_thickness_corrosion/{A,B} already
populated (both confirmed present, 69 bins each, as of 16.08.2026).

Output: results/real_campaign/joint_damage_matrix_thickness_{A,B}_{raw,
weighted}.csv (4 files) and joint_damage_matrix_thickness_corrosion_{A,B}_
{raw,weighted}_y{5,10,15,20,25}.csv (20 files) -- 24 total. Nothing else on
disk is touched; the existing stage3_joint_damage_thickness*.csv deliverables
are regenerated byte-for-byte (same computation, just also now writing the
matrices) but not otherwise changed.
"""
from pathlib import Path

import run_pipeline as rp

ROOT = Path("<campaign-root>/Simulation")


def main():
    case_dirs = rp.discover_runs(ROOT)
    print(f"discovered {len(case_dirs)} run folder(s) under {ROOT}")
    assert case_dirs, f"no run folders (owner.json found) under {ROOT}"

    sd_path = case_dirs[0] / rp.s2.SD_NAME
    sd_sum_candidates = list(case_dirs[0].glob("*.SD.sum.yaml"))
    assert sd_sum_candidates, f"no *.SD.sum.yaml found in {case_dirs[0]}"
    sd_sum_path = sd_sum_candidates[0]

    rp.keep_awake_on()
    try:
        for scenario in ["A", "B"]:
            print(f"\n=== thickness[{scenario}], uncorroded ===")
            rp.run_stage3_joints_thickness(sd_path, sd_sum_path, scenario)

        for scenario in ["A", "B"]:
            print(f"\n=== thickness[{scenario}], + corrosion (5 year-steps) ===")
            rp.run_stage3_joints_thickness_corrosion(sd_path, sd_sum_path, scenario)
    finally:
        rp.keep_awake_off()

    print("\nDone -- 24 matrix CSVs written to", rp.REAL_RESULTS_DIR)


if __name__ == "__main__":
    main()
